### PR TITLE
Add Cryptographically Secure RNG

### PR DESCRIPTION
**Pull request by benjaminBrownlee**
As a follow up to issue #97, I have modified this library to accommodate a cryptographically secure RNG.

### CODE REVIEW

**Comment by benjaminBrownlee** [comment]
It appears `BigInteger.min.js` failed some checks.  Did I make a mistake while appending the minifed code?

**Comment by peterolson** [comment]
Hi, I'm looking at the commit and it looks like it only supports running in the browser, using `window.crypto`. BigInteger.js is used on both the browser and on Node, so we need to support both environments. Also, perhaps it should fallback to `randBetween` when there is no crypto library present.

I think the failing build has to do with with adding a function without adding TypeScript definitions.

Also, there are no unit tests for this function. These should be added so that we can be more confident that it works correctly.

**Comment by benjaminBrownlee** [comment]
I believe I have an edit so that this will work in a Node environment as well as a majority of browsers, and I also threw in your suggested fallback feature if users are using an environment without crypto tools.  If you are curious, see my most recent [gist](https://gist.github.com/benjaminBrownlee/2823e06d0b455969a06a13eddbadeb48) edits.

I tried to append my minified scripts into the original minified file, which must have gone wrong.  I will re-minify the forked regular file to avoid these errors next time.

However, as mentioned before, I have no idea where to turn to do "unit tests" on my function.  Is there a preferred or formal process or host to do those?

Also, to be completely honest, I have not used TypeScript before.  I actually have used a converter tool to convert your entire library to PHP, but TypeScript is a superset of JavaScript so tools can't convert in that direction.

**Comment by peterolson** [comment]
The unit tests are located in the [spec/spec.js file](https://github.com/peterolson/BigInteger.js/blob/master/spec/spec.js). You can look through there and follow the example of the existing tests that specify what kinds of outputs we expect from the functions. You'll probably be most interested in the tests for the `randBetween` function.

The TypeScript definitions are in the [BigInteger.d.ts file](https://github.com/peterolson/BigInteger.js/blob/master/BigInteger.d.ts), which defines types and makes it more convenient for people using BigInteger.js in their TypeScript projects. The [tsDefinitions.ts](https://github.com/peterolson/BigInteger.js/blob/master/spec/tsDefinitions.ts) verifies that the library actually conforms to these type definitions.

As I said before, don't worry about the TypeScript definitions if you have trouble figuring it out, but it is important to have unit tests for every function in the library.

**Pull request closed without merging**
