### PR TITLE
Added parsing of hex string

### PR DESCRIPTION
**Pull request by jokumusic**
This is to support parsing of hex strings that begin with 0x or x

### CODE REVIEW

**Comment by peterolson** [comment]
Hex values are already supported via the second argument to `bigInt`. For example, `bigInt("ff", 16)`.

**Comment by jokumusic** [comment]
> Hex values are already supported via the second argument to `bigInt`. For example, `bigInt("ff", 16)`.

That doesn't work for packages that expect hexstrings to work. It breaks them... Adding the hex parsing lets them work.

**Comment by peterolson** [comment]
I haven't looked carefully, but this change potentially break parsing for non-hexadecimal inputs that happen to begin with 0x, such as `bigInt("0xaa12", 36)`

**Comment by jokumusic** [comment]
> I haven't looked carefully, but this change potentially break parsing for non-hexadecimal inputs that happen to begin with 0x, such as `bigInt("0xaa12", 36)`

It would break those

**Pull request closed without merging**
