### PR TITLE
Merge gh-pages and master

### PR DESCRIPTION
**Pull request by peterolson**

### CODE REVIEW

**Comment by Yaffle** [comment]
benchmark's page looks great!

**Comment by peterolson** [comment]
Thanks! And thank you for your library and benchmark page, I borrowed quite a few things from them and they gave me some motivation to think about performance more than I would have otherwise.

**Comment by Yaffle** [comment]
I am glad, that my page was useful. That is good, that you have implemented "SmallInteger", I think this is the right way to optimize operations on small integers, I found only one lib in js, which is also doing this - https://github.com/jtobey/javascript-bignum .

I found some issues with your new code:
```

//1.
      bigInt("10", 2);// `return parseInt(text, base);` - new SmallInteger(...) should be here (?)

//2.
      bigInt("10000000000000000").subtract(bigInt("10000000000000000")).toString(); //  (`arrayToSmall` - `if (length < 1) return 0;`);

//3.
      bigInt("-9007199254740991").add(bigInt("-1")).toString();// possibly, Math.abs(b) and Math.abs(a)  should be passed to `smallToArray` and `addSmall` at the end of `SmallInteger.prototype.add` 

//4.  
      bigInt("111111111111111111111111111111111111111111111111111111", 2).toString(2);
//(?)

```

**Comment by peterolson** [comment]
Thanks, I've fixed those issues, let me know if you find any other bugs

**Comment by Yaffle** [comment]
bigInt("9007199254740991").add(bigInt("1")).toString()

**Comment by peterolson** [comment]
Thanks, fixed, anything else?

**Comment by Yaffle** [comment]
Seems, that is all.

**Comment by Yaffle** [comment]
```
bigInt("10000000000000000").divide(bigInt("-10000000000000000")).toString()
```

**Comment by Yaffle** [comment]
```
 bigInt("0", 10).negate().add(bigInt("10000000000000000", 10)).toString(10)
```

**Comment by peterolson** [comment]
Спасибо, исправил.

**Comment by Yaffle** [comment]
`bigInt("0").negate().add(bigInt("-1"))` теперь приводит к "RangeError: Maximum call stack size exceeded"

**Comment by peterolson** [comment]
Так, спасибо, исправил. Минус ноль очень неприятное число)

**Comment by Yaffle** [comment]
Теперь все тесты проходят.

**Pull request merged**
