### PR TITLE
Multiplicative inverse function (modInv) added.

### PR DESCRIPTION
**Pull request by ABaptista**

### CODE REVIEW

**Comment by peterolson** [comment]
Is there a common use case for this? I don't want to make this library too big, and it seems to me that this is a fairly specialized number theory function that would rarely be used.

**Comment by ABaptista** [comment]
I understand, but this is a common function in cryptography (RSA, ElGamal, Knapsack).
So, it would be useful if anyone uses your library to implement a cryptosystem in javascript, dealing with very large numbers.
I implemented it because I'm developing a cryptography project.

**Comment by peterolson** [comment]
I see. Now that I look at this issues again, [this isn't the first time that this has been suggested](https://github.com/peterolson/BigInteger.js/issues/62) and there are other [crypto features that have been suggested as well](https://github.com/peterolson/BigInteger.js/issues/79). To be honest, part of the reason I'm hesitant to add them is because I personally don't know much about cryptography.

It could be a good idea to make a cryptography library that extends BigInteger.

By the way, I should have said this before -- thanks for your contribution. I appreciate it, even if I don't end up deciding to merge it in.

**Comment by Yaffle** [comment]
@peterolson , you could one extra file to your repository as variant

**Comment by Yaffle** [comment]
@peterolson , you have `modPow`, so `modInverse` could be added too.

**Comment by ABaptista** [comment]
@peterolson No problem, it's up to you 👍
Thank you for this library!

**Comment by peterolson** [comment]
I finally decided that I might as well include it in. Thanks

**Pull request merged**
