### PR TITLE
Add TypeScript Definition

### PR DESCRIPTION
**Pull request by toefraz**
This PR adds a TypeScript definition file that describes the shape of BigInteger.js.

It also updates `npm test` to run a test file that will break when new methods are added/removed to inform the developer that those changes should be made to the definition file too to keep it in sync.

I couldn't run the test suite without upgrading the Karma PhantomJS runner. Let me know if there are issues upgrading it.

### CODE REVIEW

**Comment by peterolson** [comment]
Thanks, looks good to me.

**Comment by toefraz** [comment]
Thanks! Any idea when a new release with this will be published?

**Comment by peterolson** [comment]
I just added a release now

**Comment by toefraz** [comment]
Awesome, I appreciate it. Is it a problem that the version in package.json is the same as the previous release?

**Comment by zokker13** [comment]
How can you actually use this? I get 'cant find module' all the time.
This is my import:
`import * as bigInt from 'big-integer'

**Comment by toefraz** [comment]
Yep, that's how it should be imported. It could something else going on with your TypeScript configuration.

**Comment by toefraz** [comment]
@zokker13 Sorry to pry, but I just took a look at the tsconfig for your "node-manipulate_my_memory" project, and I believe moduleResolution should be set to "node", not "classic". Hopefully that helps

**Comment by toefraz** [comment]
Also lol at the commits

**Comment by zokker13** [comment]
@toefraz That did the trick, thank you very much! That was a rough night :()

Sry for derailing this PR. Wonderful work!

**Pull request merged**
