### PR TITLE
BigInteger.toArray

### PR DESCRIPTION
**Pull request by matthewleon**
addresses https://github.com/peterolson/BigInteger.js/issues/123

This code uses `Array.fill`, which breaks compatibility with legacy browsers. If this is undesirable, I can modify the code to maintain compatibility, probably at the cost of some performance.

### CODE REVIEW

**Comment by peterolson** [comment]
Hey, thanks, it looks great, you seem to have found your way around the project well. I just have two suggestions before I merge it in:

- The part you added to README.md documentation shows `toArray` returning strings (it looks like it's copied from the `toString` documentation)
 - As you mentioned, `Array.fill` breaks compatibility with legacy environments (and it requires changing to ChromeHeadless instead of PhantomJS, which seems to be breaking the Travis CI build for some reason). I'd prefer to keep compatibility here.

Thanks!

**Comment by matthewleon** [comment]
Okay, I believe this to be ready for review again. Thanks for your comments.

**Comment by matthewleon** [comment]
I'll try to please coveralls.

**Comment by matthewleon** [comment]
Okay, we're good with coveralls :). Things should be truly reviewable now.

**Comment by peterolson** [comment]
Looks good to me, thanks!

**Pull request merged**
